// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai_chat_message_protocol.proto
// Protobuf Java Version: 4.29.3

package edu.cust.secad.chat.proto;

public final class AiChatMessageProtocol {
  private AiChatMessageProtocol() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AiChatMessageProtocol.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMessageProtocolFormOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.cust.secad.chat.proto.ChatMessageProtocolForm)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 上一条消息的unionId
     * </pre>
     *
     * <code>string lastUid = 1;</code>
     * @return The lastUid.
     */
    String getLastUid();
    /**
     * <pre>
     * 上一条消息的unionId
     * </pre>
     *
     * <code>string lastUid = 1;</code>
     * @return The bytes for lastUid.
     */
    com.google.protobuf.ByteString
        getLastUidBytes();

    /**
     * <pre>
     * 发送时间（时间戳）
     * </pre>
     *
     * <code>string sendTime = 2;</code>
     * @return The sendTime.
     */
    String getSendTime();
    /**
     * <pre>
     * 发送时间（时间戳）
     * </pre>
     *
     * <code>string sendTime = 2;</code>
     * @return The bytes for sendTime.
     */
    com.google.protobuf.ByteString
        getSendTimeBytes();

    /**
     * <pre>
     * 自增id，如果数据包需要拆分的话
     * </pre>
     *
     * <code>string pkgId = 3;</code>
     * @return The pkgId.
     */
    String getPkgId();
    /**
     * <pre>
     * 自增id，如果数据包需要拆分的话
     * </pre>
     *
     * <code>string pkgId = 3;</code>
     * @return The bytes for pkgId.
     */
    com.google.protobuf.ByteString
        getPkgIdBytes();

    /**
     * <pre>
     * 发送者id。用户或AI
     * </pre>
     *
     * <code>string senderId = 4;</code>
     * @return The senderId.
     */
    String getSenderId();
    /**
     * <pre>
     * 发送者id。用户或AI
     * </pre>
     *
     * <code>string senderId = 4;</code>
     * @return The bytes for senderId.
     */
    com.google.protobuf.ByteString
        getSenderIdBytes();

    /**
     * <pre>
     * 接受者id。用户或AI
     * </pre>
     *
     * <code>string rcvId = 5;</code>
     * @return The rcvId.
     */
    String getRcvId();
    /**
     * <pre>
     * 接受者id。用户或AI
     * </pre>
     *
     * <code>string rcvId = 5;</code>
     * @return The bytes for rcvId.
     */
    com.google.protobuf.ByteString
        getRcvIdBytes();

    /**
     * <pre>
     * 用于配对发送者/接受者/topic id
     * </pre>
     *
     * <code>string unionId = 6;</code>
     * @return The unionId.
     */
    String getUnionId();
    /**
     * <pre>
     * 用于配对发送者/接受者/topic id
     * </pre>
     *
     * <code>string unionId = 6;</code>
     * @return The bytes for unionId.
     */
    com.google.protobuf.ByteString
        getUnionIdBytes();

    /**
     * <pre>
     * 消息长度
     * </pre>
     *
     * <code>int32 len = 7;</code>
     * @return The len.
     */
    int getLen();

    /**
     * <pre>
     * 0-文本 / 1-mp3 / 2-心跳 / 3-问候 msgType
     * </pre>
     *
     * <code>int32 msgType = 8;</code>
     * @return The msgType.
     */
    int getMsgType();

    /**
     * <pre>
     * 消息内容 (字节数组)
     * </pre>
     *
     * <code>bytes messageContent = 9;</code>
     * @return The messageContent.
     */
    com.google.protobuf.ByteString getMessageContent();
  }
  /**
   * <pre>
   * 定义 ChatMessageProtocolForm 消息
   * </pre>
   *
   * Protobuf type {@code edu.cust.secad.chat.proto.ChatMessageProtocolForm}
   */
  public static final class ChatMessageProtocolForm extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:edu.cust.secad.chat.proto.ChatMessageProtocolForm)
      ChatMessageProtocolFormOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ChatMessageProtocolForm.class.getName());
    }
    // Use ChatMessageProtocolForm.newBuilder() to construct.
    private ChatMessageProtocolForm(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ChatMessageProtocolForm() {
      lastUid_ = "";
      sendTime_ = "";
      pkgId_ = "";
      senderId_ = "";
      rcvId_ = "";
      unionId_ = "";
      messageContent_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AiChatMessageProtocol.internal_static_edu_cust_secad_chat_proto_ChatMessageProtocolForm_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AiChatMessageProtocol.internal_static_edu_cust_secad_chat_proto_ChatMessageProtocolForm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatMessageProtocolForm.class, Builder.class);
    }

    public static final int LASTUID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object lastUid_ = "";
    /**
     * <pre>
     * 上一条消息的unionId
     * </pre>
     *
     * <code>string lastUid = 1;</code>
     * @return The lastUid.
     */
    @Override
    public String getLastUid() {
      Object ref = lastUid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        lastUid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 上一条消息的unionId
     * </pre>
     *
     * <code>string lastUid = 1;</code>
     * @return The bytes for lastUid.
     */
    @Override
    public com.google.protobuf.ByteString
        getLastUidBytes() {
      Object ref = lastUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        lastUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTIME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object sendTime_ = "";
    /**
     * <pre>
     * 发送时间（时间戳）
     * </pre>
     *
     * <code>string sendTime = 2;</code>
     * @return The sendTime.
     */
    @Override
    public String getSendTime() {
      Object ref = sendTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sendTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发送时间（时间戳）
     * </pre>
     *
     * <code>string sendTime = 2;</code>
     * @return The bytes for sendTime.
     */
    @Override
    public com.google.protobuf.ByteString
        getSendTimeBytes() {
      Object ref = sendTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sendTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PKGID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object pkgId_ = "";
    /**
     * <pre>
     * 自增id，如果数据包需要拆分的话
     * </pre>
     *
     * <code>string pkgId = 3;</code>
     * @return The pkgId.
     */
    @Override
    public String getPkgId() {
      Object ref = pkgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pkgId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 自增id，如果数据包需要拆分的话
     * </pre>
     *
     * <code>string pkgId = 3;</code>
     * @return The bytes for pkgId.
     */
    @Override
    public com.google.protobuf.ByteString
        getPkgIdBytes() {
      Object ref = pkgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pkgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERID_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object senderId_ = "";
    /**
     * <pre>
     * 发送者id。用户或AI
     * </pre>
     *
     * <code>string senderId = 4;</code>
     * @return The senderId.
     */
    @Override
    public String getSenderId() {
      Object ref = senderId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        senderId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发送者id。用户或AI
     * </pre>
     *
     * <code>string senderId = 4;</code>
     * @return The bytes for senderId.
     */
    @Override
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      Object ref = senderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RCVID_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile Object rcvId_ = "";
    /**
     * <pre>
     * 接受者id。用户或AI
     * </pre>
     *
     * <code>string rcvId = 5;</code>
     * @return The rcvId.
     */
    @Override
    public String getRcvId() {
      Object ref = rcvId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        rcvId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 接受者id。用户或AI
     * </pre>
     *
     * <code>string rcvId = 5;</code>
     * @return The bytes for rcvId.
     */
    @Override
    public com.google.protobuf.ByteString
        getRcvIdBytes() {
      Object ref = rcvId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rcvId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UNIONID_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile Object unionId_ = "";
    /**
     * <pre>
     * 用于配对发送者/接受者/topic id
     * </pre>
     *
     * <code>string unionId = 6;</code>
     * @return The unionId.
     */
    @Override
    public String getUnionId() {
      Object ref = unionId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        unionId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用于配对发送者/接受者/topic id
     * </pre>
     *
     * <code>string unionId = 6;</code>
     * @return The bytes for unionId.
     */
    @Override
    public com.google.protobuf.ByteString
        getUnionIdBytes() {
      Object ref = unionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        unionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEN_FIELD_NUMBER = 7;
    private int len_ = 0;
    /**
     * <pre>
     * 消息长度
     * </pre>
     *
     * <code>int32 len = 7;</code>
     * @return The len.
     */
    @Override
    public int getLen() {
      return len_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 8;
    private int msgType_ = 0;
    /**
     * <pre>
     * 0-文本 / 1-mp3 / 2-心跳 / 3-问候 msgType
     * </pre>
     *
     * <code>int32 msgType = 8;</code>
     * @return The msgType.
     */
    @Override
    public int getMsgType() {
      return msgType_;
    }

    public static final int MESSAGECONTENT_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString messageContent_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 消息内容 (字节数组)
     * </pre>
     *
     * <code>bytes messageContent = 9;</code>
     * @return The messageContent.
     */
    @Override
    public com.google.protobuf.ByteString getMessageContent() {
      return messageContent_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastUid_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, lastUid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sendTime_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, sendTime_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pkgId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, pkgId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, senderId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rcvId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, rcvId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unionId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, unionId_);
      }
      if (len_ != 0) {
        output.writeInt32(7, len_);
      }
      if (msgType_ != 0) {
        output.writeInt32(8, msgType_);
      }
      if (!messageContent_.isEmpty()) {
        output.writeBytes(9, messageContent_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastUid_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, lastUid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sendTime_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sendTime_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pkgId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, pkgId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, senderId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rcvId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, rcvId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unionId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, unionId_);
      }
      if (len_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, len_);
      }
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, msgType_);
      }
      if (!messageContent_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, messageContent_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ChatMessageProtocolForm)) {
        return super.equals(obj);
      }
      ChatMessageProtocolForm other = (ChatMessageProtocolForm) obj;

      if (!getLastUid()
          .equals(other.getLastUid())) return false;
      if (!getSendTime()
          .equals(other.getSendTime())) return false;
      if (!getPkgId()
          .equals(other.getPkgId())) return false;
      if (!getSenderId()
          .equals(other.getSenderId())) return false;
      if (!getRcvId()
          .equals(other.getRcvId())) return false;
      if (!getUnionId()
          .equals(other.getUnionId())) return false;
      if (getLen()
          != other.getLen()) return false;
      if (getMsgType()
          != other.getMsgType()) return false;
      if (!getMessageContent()
          .equals(other.getMessageContent())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LASTUID_FIELD_NUMBER;
      hash = (53 * hash) + getLastUid().hashCode();
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + getSendTime().hashCode();
      hash = (37 * hash) + PKGID_FIELD_NUMBER;
      hash = (53 * hash) + getPkgId().hashCode();
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderId().hashCode();
      hash = (37 * hash) + RCVID_FIELD_NUMBER;
      hash = (53 * hash) + getRcvId().hashCode();
      hash = (37 * hash) + UNIONID_FIELD_NUMBER;
      hash = (53 * hash) + getUnionId().hashCode();
      hash = (37 * hash) + LEN_FIELD_NUMBER;
      hash = (53 * hash) + getLen();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + MESSAGECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getMessageContent().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ChatMessageProtocolForm parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMessageProtocolForm parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMessageProtocolForm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMessageProtocolForm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMessageProtocolForm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMessageProtocolForm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMessageProtocolForm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ChatMessageProtocolForm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ChatMessageProtocolForm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ChatMessageProtocolForm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatMessageProtocolForm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ChatMessageProtocolForm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatMessageProtocolForm prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 定义 ChatMessageProtocolForm 消息
     * </pre>
     *
     * Protobuf type {@code edu.cust.secad.chat.proto.ChatMessageProtocolForm}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.cust.secad.chat.proto.ChatMessageProtocolForm)
        ChatMessageProtocolFormOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AiChatMessageProtocol.internal_static_edu_cust_secad_chat_proto_ChatMessageProtocolForm_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AiChatMessageProtocol.internal_static_edu_cust_secad_chat_proto_ChatMessageProtocolForm_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChatMessageProtocolForm.class, Builder.class);
      }

      // Construct using edu.cust.secad.chat.proto.AiChatMessageProtocol.ChatMessageProtocolForm.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        lastUid_ = "";
        sendTime_ = "";
        pkgId_ = "";
        senderId_ = "";
        rcvId_ = "";
        unionId_ = "";
        len_ = 0;
        msgType_ = 0;
        messageContent_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AiChatMessageProtocol.internal_static_edu_cust_secad_chat_proto_ChatMessageProtocolForm_descriptor;
      }

      @Override
      public ChatMessageProtocolForm getDefaultInstanceForType() {
        return ChatMessageProtocolForm.getDefaultInstance();
      }

      @Override
      public ChatMessageProtocolForm build() {
        ChatMessageProtocolForm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ChatMessageProtocolForm buildPartial() {
        ChatMessageProtocolForm result = new ChatMessageProtocolForm(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ChatMessageProtocolForm result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.lastUid_ = lastUid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sendTime_ = sendTime_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.pkgId_ = pkgId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.senderId_ = senderId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.rcvId_ = rcvId_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.unionId_ = unionId_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.len_ = len_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.msgType_ = msgType_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.messageContent_ = messageContent_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChatMessageProtocolForm) {
          return mergeFrom((ChatMessageProtocolForm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChatMessageProtocolForm other) {
        if (other == ChatMessageProtocolForm.getDefaultInstance()) return this;
        if (!other.getLastUid().isEmpty()) {
          lastUid_ = other.lastUid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getSendTime().isEmpty()) {
          sendTime_ = other.sendTime_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getPkgId().isEmpty()) {
          pkgId_ = other.pkgId_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getSenderId().isEmpty()) {
          senderId_ = other.senderId_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getRcvId().isEmpty()) {
          rcvId_ = other.rcvId_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getUnionId().isEmpty()) {
          unionId_ = other.unionId_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.getLen() != 0) {
          setLen(other.getLen());
        }
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (other.getMessageContent() != com.google.protobuf.ByteString.EMPTY) {
          setMessageContent(other.getMessageContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                lastUid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                sendTime_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                pkgId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                senderId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                rcvId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                unionId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 56: {
                len_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                msgType_ = input.readInt32();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 74: {
                messageContent_ = input.readBytes();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object lastUid_ = "";
      /**
       * <pre>
       * 上一条消息的unionId
       * </pre>
       *
       * <code>string lastUid = 1;</code>
       * @return The lastUid.
       */
      public String getLastUid() {
        Object ref = lastUid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          lastUid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 上一条消息的unionId
       * </pre>
       *
       * <code>string lastUid = 1;</code>
       * @return The bytes for lastUid.
       */
      public com.google.protobuf.ByteString
          getLastUidBytes() {
        Object ref = lastUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          lastUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 上一条消息的unionId
       * </pre>
       *
       * <code>string lastUid = 1;</code>
       * @param value The lastUid to set.
       * @return This builder for chaining.
       */
      public Builder setLastUid(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        lastUid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 上一条消息的unionId
       * </pre>
       *
       * <code>string lastUid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUid() {
        lastUid_ = getDefaultInstance().getLastUid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 上一条消息的unionId
       * </pre>
       *
       * <code>string lastUid = 1;</code>
       * @param value The bytes for lastUid to set.
       * @return This builder for chaining.
       */
      public Builder setLastUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        lastUid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object sendTime_ = "";
      /**
       * <pre>
       * 发送时间（时间戳）
       * </pre>
       *
       * <code>string sendTime = 2;</code>
       * @return The sendTime.
       */
      public String getSendTime() {
        Object ref = sendTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sendTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 发送时间（时间戳）
       * </pre>
       *
       * <code>string sendTime = 2;</code>
       * @return The bytes for sendTime.
       */
      public com.google.protobuf.ByteString
          getSendTimeBytes() {
        Object ref = sendTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sendTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发送时间（时间戳）
       * </pre>
       *
       * <code>string sendTime = 2;</code>
       * @param value The sendTime to set.
       * @return This builder for chaining.
       */
      public Builder setSendTime(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        sendTime_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送时间（时间戳）
       * </pre>
       *
       * <code>string sendTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendTime() {
        sendTime_ = getDefaultInstance().getSendTime();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送时间（时间戳）
       * </pre>
       *
       * <code>string sendTime = 2;</code>
       * @param value The bytes for sendTime to set.
       * @return This builder for chaining.
       */
      public Builder setSendTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sendTime_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Object pkgId_ = "";
      /**
       * <pre>
       * 自增id，如果数据包需要拆分的话
       * </pre>
       *
       * <code>string pkgId = 3;</code>
       * @return The pkgId.
       */
      public String getPkgId() {
        Object ref = pkgId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          pkgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 自增id，如果数据包需要拆分的话
       * </pre>
       *
       * <code>string pkgId = 3;</code>
       * @return The bytes for pkgId.
       */
      public com.google.protobuf.ByteString
          getPkgIdBytes() {
        Object ref = pkgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pkgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 自增id，如果数据包需要拆分的话
       * </pre>
       *
       * <code>string pkgId = 3;</code>
       * @param value The pkgId to set.
       * @return This builder for chaining.
       */
      public Builder setPkgId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        pkgId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 自增id，如果数据包需要拆分的话
       * </pre>
       *
       * <code>string pkgId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPkgId() {
        pkgId_ = getDefaultInstance().getPkgId();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 自增id，如果数据包需要拆分的话
       * </pre>
       *
       * <code>string pkgId = 3;</code>
       * @param value The bytes for pkgId to set.
       * @return This builder for chaining.
       */
      public Builder setPkgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        pkgId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private Object senderId_ = "";
      /**
       * <pre>
       * 发送者id。用户或AI
       * </pre>
       *
       * <code>string senderId = 4;</code>
       * @return The senderId.
       */
      public String getSenderId() {
        Object ref = senderId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          senderId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 发送者id。用户或AI
       * </pre>
       *
       * <code>string senderId = 4;</code>
       * @return The bytes for senderId.
       */
      public com.google.protobuf.ByteString
          getSenderIdBytes() {
        Object ref = senderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          senderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发送者id。用户或AI
       * </pre>
       *
       * <code>string senderId = 4;</code>
       * @param value The senderId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        senderId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送者id。用户或AI
       * </pre>
       *
       * <code>string senderId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderId() {
        senderId_ = getDefaultInstance().getSenderId();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送者id。用户或AI
       * </pre>
       *
       * <code>string senderId = 4;</code>
       * @param value The bytes for senderId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        senderId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private Object rcvId_ = "";
      /**
       * <pre>
       * 接受者id。用户或AI
       * </pre>
       *
       * <code>string rcvId = 5;</code>
       * @return The rcvId.
       */
      public String getRcvId() {
        Object ref = rcvId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          rcvId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 接受者id。用户或AI
       * </pre>
       *
       * <code>string rcvId = 5;</code>
       * @return The bytes for rcvId.
       */
      public com.google.protobuf.ByteString
          getRcvIdBytes() {
        Object ref = rcvId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          rcvId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 接受者id。用户或AI
       * </pre>
       *
       * <code>string rcvId = 5;</code>
       * @param value The rcvId to set.
       * @return This builder for chaining.
       */
      public Builder setRcvId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        rcvId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接受者id。用户或AI
       * </pre>
       *
       * <code>string rcvId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRcvId() {
        rcvId_ = getDefaultInstance().getRcvId();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接受者id。用户或AI
       * </pre>
       *
       * <code>string rcvId = 5;</code>
       * @param value The bytes for rcvId to set.
       * @return This builder for chaining.
       */
      public Builder setRcvIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        rcvId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private Object unionId_ = "";
      /**
       * <pre>
       * 用于配对发送者/接受者/topic id
       * </pre>
       *
       * <code>string unionId = 6;</code>
       * @return The unionId.
       */
      public String getUnionId() {
        Object ref = unionId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          unionId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 用于配对发送者/接受者/topic id
       * </pre>
       *
       * <code>string unionId = 6;</code>
       * @return The bytes for unionId.
       */
      public com.google.protobuf.ByteString
          getUnionIdBytes() {
        Object ref = unionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          unionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用于配对发送者/接受者/topic id
       * </pre>
       *
       * <code>string unionId = 6;</code>
       * @param value The unionId to set.
       * @return This builder for chaining.
       */
      public Builder setUnionId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        unionId_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用于配对发送者/接受者/topic id
       * </pre>
       *
       * <code>string unionId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnionId() {
        unionId_ = getDefaultInstance().getUnionId();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用于配对发送者/接受者/topic id
       * </pre>
       *
       * <code>string unionId = 6;</code>
       * @param value The bytes for unionId to set.
       * @return This builder for chaining.
       */
      public Builder setUnionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        unionId_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private int len_ ;
      /**
       * <pre>
       * 消息长度
       * </pre>
       *
       * <code>int32 len = 7;</code>
       * @return The len.
       */
      @Override
      public int getLen() {
        return len_;
      }
      /**
       * <pre>
       * 消息长度
       * </pre>
       *
       * <code>int32 len = 7;</code>
       * @param value The len to set.
       * @return This builder for chaining.
       */
      public Builder setLen(int value) {

        len_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息长度
       * </pre>
       *
       * <code>int32 len = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLen() {
        bitField0_ = (bitField0_ & ~0x00000040);
        len_ = 0;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <pre>
       * 0-文本 / 1-mp3 / 2-心跳 / 3-问候 msgType
       * </pre>
       *
       * <code>int32 msgType = 8;</code>
       * @return The msgType.
       */
      @Override
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <pre>
       * 0-文本 / 1-mp3 / 2-心跳 / 3-问候 msgType
       * </pre>
       *
       * <code>int32 msgType = 8;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(int value) {

        msgType_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 0-文本 / 1-mp3 / 2-心跳 / 3-问候 msgType
       * </pre>
       *
       * <code>int32 msgType = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString messageContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 消息内容 (字节数组)
       * </pre>
       *
       * <code>bytes messageContent = 9;</code>
       * @return The messageContent.
       */
      @Override
      public com.google.protobuf.ByteString getMessageContent() {
        return messageContent_;
      }
      /**
       * <pre>
       * 消息内容 (字节数组)
       * </pre>
       *
       * <code>bytes messageContent = 9;</code>
       * @param value The messageContent to set.
       * @return This builder for chaining.
       */
      public Builder setMessageContent(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        messageContent_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容 (字节数组)
       * </pre>
       *
       * <code>bytes messageContent = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageContent() {
        bitField0_ = (bitField0_ & ~0x00000100);
        messageContent_ = getDefaultInstance().getMessageContent();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:edu.cust.secad.chat.proto.ChatMessageProtocolForm)
    }

    // @@protoc_insertion_point(class_scope:edu.cust.secad.chat.proto.ChatMessageProtocolForm)
    private static final ChatMessageProtocolForm DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ChatMessageProtocolForm();
    }

    public static ChatMessageProtocolForm getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMessageProtocolForm>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessageProtocolForm>() {
      @Override
      public ChatMessageProtocolForm parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChatMessageProtocolForm> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ChatMessageProtocolForm> getParserForType() {
      return PARSER;
    }

    @Override
    public ChatMessageProtocolForm getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_cust_secad_chat_proto_ChatMessageProtocolForm_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_cust_secad_chat_proto_ChatMessageProtocolForm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036ai_chat_message_protocol.proto\022\031edu.cu" +
      "st.secad.chat.proto\"\263\001\n\027ChatMessageProto" +
      "colForm\022\017\n\007lastUid\030\001 \001(\t\022\020\n\010sendTime\030\002 \001" +
      "(\t\022\r\n\005pkgId\030\003 \001(\t\022\020\n\010senderId\030\004 \001(\t\022\r\n\005r" +
      "cvId\030\005 \001(\t\022\017\n\007unionId\030\006 \001(\t\022\013\n\003len\030\007 \001(\005" +
      "\022\017\n\007msgType\030\010 \001(\005\022\026\n\016messageContent\030\t \001(" +
      "\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_edu_cust_secad_chat_proto_ChatMessageProtocolForm_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_edu_cust_secad_chat_proto_ChatMessageProtocolForm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_edu_cust_secad_chat_proto_ChatMessageProtocolForm_descriptor,
        new String[] { "LastUid", "SendTime", "PkgId", "SenderId", "RcvId", "UnionId", "Len", "MsgType", "MessageContent", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
