// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chat_message_protocol.proto
// Protobuf Java Version: 4.28.2

package edu.cust.secad.chat.proto;

public final class ChatMessageProtocol {
  private ChatMessageProtocol() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      ChatMessageProtocol.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMessageProtocolFormOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.cust.mccat.huatuo.chat.proto.ChatMessageProtocolForm)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 发送人 ID
     * </pre>
     *
     * <code>string senderId = 1;</code>
     * @return The senderId.
     */
    String getSenderId();
    /**
     * <pre>
     * 发送人 ID
     * </pre>
     *
     * <code>string senderId = 1;</code>
     * @return The bytes for senderId.
     */
    com.google.protobuf.ByteString
        getSenderIdBytes();

    /**
     * <pre>
     * 群聊 ID
     * </pre>
     *
     * <code>string groupId = 2;</code>
     * @return The groupId.
     */
    String getGroupId();
    /**
     * <pre>
     * 群聊 ID
     * </pre>
     *
     * <code>string groupId = 2;</code>
     * @return The bytes for groupId.
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>int32 messageType = 3;</code>
     * @return The messageType.
     */
    int getMessageType();

    /**
     * <pre>
     * 消息内容 (字节数组)
     * </pre>
     *
     * <code>bytes messageContent = 4;</code>
     * @return The messageContent.
     */
    com.google.protobuf.ByteString getMessageContent();

    /**
     * <pre>
     * 发送时间 (时间戳)
     * </pre>
     *
     * <code>int64 sendTime = 5;</code>
     * @return The sendTime.
     */
    long getSendTime();
  }
  /**
   * <pre>
   * 定义 ChatMessageProtocolForm 消息
   * </pre>
   *
   * Protobuf type {@code edu.cust.mccat.huatuo.chat.proto.ChatMessageProtocolForm}
   */
  public static final class ChatMessageProtocolForm extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:edu.cust.mccat.huatuo.chat.proto.ChatMessageProtocolForm)
      ChatMessageProtocolFormOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        ChatMessageProtocolForm.class.getName());
    }
    // Use ChatMessageProtocolForm.newBuilder() to construct.
    private ChatMessageProtocolForm(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ChatMessageProtocolForm() {
      senderId_ = "";
      groupId_ = "";
      messageContent_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChatMessageProtocol.internal_static_edu_cust_mccat_huatuo_chat_proto_ChatMessageProtocolForm_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChatMessageProtocol.internal_static_edu_cust_mccat_huatuo_chat_proto_ChatMessageProtocolForm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatMessageProtocolForm.class, Builder.class);
    }

    public static final int SENDERID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object senderId_ = "";
    /**
     * <pre>
     * 发送人 ID
     * </pre>
     *
     * <code>string senderId = 1;</code>
     * @return The senderId.
     */
    @Override
    public String getSenderId() {
      Object ref = senderId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        senderId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发送人 ID
     * </pre>
     *
     * <code>string senderId = 1;</code>
     * @return The bytes for senderId.
     */
    @Override
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      Object ref = senderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object groupId_ = "";
    /**
     * <pre>
     * 群聊 ID
     * </pre>
     *
     * <code>string groupId = 2;</code>
     * @return The groupId.
     */
    @Override
    public String getGroupId() {
      Object ref = groupId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 群聊 ID
     * </pre>
     *
     * <code>string groupId = 2;</code>
     * @return The bytes for groupId.
     */
    @Override
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      Object ref = groupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 3;
    private int messageType_ = 0;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>int32 messageType = 3;</code>
     * @return The messageType.
     */
    @Override
    public int getMessageType() {
      return messageType_;
    }

    public static final int MESSAGECONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString messageContent_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 消息内容 (字节数组)
     * </pre>
     *
     * <code>bytes messageContent = 4;</code>
     * @return The messageContent.
     */
    @Override
    public com.google.protobuf.ByteString getMessageContent() {
      return messageContent_;
    }

    public static final int SENDTIME_FIELD_NUMBER = 5;
    private long sendTime_ = 0L;
    /**
     * <pre>
     * 发送时间 (时间戳)
     * </pre>
     *
     * <code>int64 sendTime = 5;</code>
     * @return The sendTime.
     */
    @Override
    public long getSendTime() {
      return sendTime_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, senderId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, groupId_);
      }
      if (messageType_ != 0) {
        output.writeInt32(3, messageType_);
      }
      if (!messageContent_.isEmpty()) {
        output.writeBytes(4, messageContent_);
      }
      if (sendTime_ != 0L) {
        output.writeInt64(5, sendTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, senderId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, groupId_);
      }
      if (messageType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, messageType_);
      }
      if (!messageContent_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, messageContent_);
      }
      if (sendTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, sendTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ChatMessageProtocolForm)) {
        return super.equals(obj);
      }
      ChatMessageProtocolForm other = (ChatMessageProtocolForm) obj;

      if (!getSenderId()
          .equals(other.getSenderId())) return false;
      if (!getGroupId()
          .equals(other.getGroupId())) return false;
      if (getMessageType()
          != other.getMessageType()) return false;
      if (!getMessageContent()
          .equals(other.getMessageContent())) return false;
      if (getSendTime()
          != other.getSendTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderId().hashCode();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType();
      hash = (37 * hash) + MESSAGECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getMessageContent().hashCode();
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ChatMessageProtocolForm parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMessageProtocolForm parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMessageProtocolForm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMessageProtocolForm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMessageProtocolForm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMessageProtocolForm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMessageProtocolForm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ChatMessageProtocolForm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ChatMessageProtocolForm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ChatMessageProtocolForm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatMessageProtocolForm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ChatMessageProtocolForm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatMessageProtocolForm prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 定义 ChatMessageProtocolForm 消息
     * </pre>
     *
     * Protobuf type {@code edu.cust.mccat.huatuo.chat.proto.ChatMessageProtocolForm}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.cust.mccat.huatuo.chat.proto.ChatMessageProtocolForm)
        ChatMessageProtocolFormOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChatMessageProtocol.internal_static_edu_cust_mccat_huatuo_chat_proto_ChatMessageProtocolForm_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChatMessageProtocol.internal_static_edu_cust_mccat_huatuo_chat_proto_ChatMessageProtocolForm_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChatMessageProtocolForm.class, Builder.class);
      }

      // Construct using edu.cust.mccat.huatuo.chat.proto.ChatMessageProtocol.ChatMessageProtocolForm.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        senderId_ = "";
        groupId_ = "";
        messageType_ = 0;
        messageContent_ = com.google.protobuf.ByteString.EMPTY;
        sendTime_ = 0L;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChatMessageProtocol.internal_static_edu_cust_mccat_huatuo_chat_proto_ChatMessageProtocolForm_descriptor;
      }

      @Override
      public ChatMessageProtocolForm getDefaultInstanceForType() {
        return ChatMessageProtocolForm.getDefaultInstance();
      }

      @Override
      public ChatMessageProtocolForm build() {
        ChatMessageProtocolForm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ChatMessageProtocolForm buildPartial() {
        ChatMessageProtocolForm result = new ChatMessageProtocolForm(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ChatMessageProtocolForm result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.senderId_ = senderId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.groupId_ = groupId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.messageType_ = messageType_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.messageContent_ = messageContent_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.sendTime_ = sendTime_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChatMessageProtocolForm) {
          return mergeFrom((ChatMessageProtocolForm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChatMessageProtocolForm other) {
        if (other == ChatMessageProtocolForm.getDefaultInstance()) return this;
        if (!other.getSenderId().isEmpty()) {
          senderId_ = other.senderId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getMessageType() != 0) {
          setMessageType(other.getMessageType());
        }
        if (other.getMessageContent() != com.google.protobuf.ByteString.EMPTY) {
          setMessageContent(other.getMessageContent());
        }
        if (other.getSendTime() != 0L) {
          setSendTime(other.getSendTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                senderId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                groupId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                messageType_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                messageContent_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                sendTime_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object senderId_ = "";
      /**
       * <pre>
       * 发送人 ID
       * </pre>
       *
       * <code>string senderId = 1;</code>
       * @return The senderId.
       */
      public String getSenderId() {
        Object ref = senderId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          senderId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 发送人 ID
       * </pre>
       *
       * <code>string senderId = 1;</code>
       * @return The bytes for senderId.
       */
      public com.google.protobuf.ByteString
          getSenderIdBytes() {
        Object ref = senderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          senderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发送人 ID
       * </pre>
       *
       * <code>string senderId = 1;</code>
       * @param value The senderId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        senderId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送人 ID
       * </pre>
       *
       * <code>string senderId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderId() {
        senderId_ = getDefaultInstance().getSenderId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送人 ID
       * </pre>
       *
       * <code>string senderId = 1;</code>
       * @param value The bytes for senderId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        senderId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object groupId_ = "";
      /**
       * <pre>
       * 群聊 ID
       * </pre>
       *
       * <code>string groupId = 2;</code>
       * @return The groupId.
       */
      public String getGroupId() {
        Object ref = groupId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 群聊 ID
       * </pre>
       *
       * <code>string groupId = 2;</code>
       * @return The bytes for groupId.
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 群聊 ID
       * </pre>
       *
       * <code>string groupId = 2;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        groupId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群聊 ID
       * </pre>
       *
       * <code>string groupId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        groupId_ = getDefaultInstance().getGroupId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 群聊 ID
       * </pre>
       *
       * <code>string groupId = 2;</code>
       * @param value The bytes for groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        groupId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int messageType_ ;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>int32 messageType = 3;</code>
       * @return The messageType.
       */
      @Override
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>int32 messageType = 3;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(int value) {

        messageType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>int32 messageType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        messageType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString messageContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 消息内容 (字节数组)
       * </pre>
       *
       * <code>bytes messageContent = 4;</code>
       * @return The messageContent.
       */
      @Override
      public com.google.protobuf.ByteString getMessageContent() {
        return messageContent_;
      }
      /**
       * <pre>
       * 消息内容 (字节数组)
       * </pre>
       *
       * <code>bytes messageContent = 4;</code>
       * @param value The messageContent to set.
       * @return This builder for chaining.
       */
      public Builder setMessageContent(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        messageContent_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息内容 (字节数组)
       * </pre>
       *
       * <code>bytes messageContent = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageContent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        messageContent_ = getDefaultInstance().getMessageContent();
        onChanged();
        return this;
      }

      private long sendTime_ ;
      /**
       * <pre>
       * 发送时间 (时间戳)
       * </pre>
       *
       * <code>int64 sendTime = 5;</code>
       * @return The sendTime.
       */
      @Override
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <pre>
       * 发送时间 (时间戳)
       * </pre>
       *
       * <code>int64 sendTime = 5;</code>
       * @param value The sendTime to set.
       * @return This builder for chaining.
       */
      public Builder setSendTime(long value) {

        sendTime_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送时间 (时间戳)
       * </pre>
       *
       * <code>int64 sendTime = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sendTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:edu.cust.mccat.huatuo.chat.proto.ChatMessageProtocolForm)
    }

    // @@protoc_insertion_point(class_scope:edu.cust.mccat.huatuo.chat.proto.ChatMessageProtocolForm)
    private static final ChatMessageProtocolForm DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ChatMessageProtocolForm();
    }

    public static ChatMessageProtocolForm getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMessageProtocolForm>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessageProtocolForm>() {
      @Override
      public ChatMessageProtocolForm parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChatMessageProtocolForm> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ChatMessageProtocolForm> getParserForType() {
      return PARSER;
    }

    @Override
    public ChatMessageProtocolForm getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_cust_mccat_huatuo_chat_proto_ChatMessageProtocolForm_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_cust_mccat_huatuo_chat_proto_ChatMessageProtocolForm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033chat_message_protocol.proto\022 edu.cust." +
      "mccat.huatuo.chat.proto\"{\n\027ChatMessagePr" +
      "otocolForm\022\020\n\010senderId\030\001 \001(\t\022\017\n\007groupId\030" +
      "\002 \001(\t\022\023\n\013messageType\030\003 \001(\005\022\026\n\016messageCon" +
      "tent\030\004 \001(\014\022\020\n\010sendTime\030\005 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_edu_cust_mccat_huatuo_chat_proto_ChatMessageProtocolForm_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_edu_cust_mccat_huatuo_chat_proto_ChatMessageProtocolForm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_edu_cust_mccat_huatuo_chat_proto_ChatMessageProtocolForm_descriptor,
        new String[] { "SenderId", "GroupId", "MessageType", "MessageContent", "SendTime", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
